### ISSUE TITLE
advised to support set tls finger

### ISSUE THREAD

**Issue by Nyx2022** [projectdiscovery/rawhttp#104] opened 2023-03-10 07:34 UTC
### Please describe your feature request:
i hope can set a  tls fingerprint with https://github.com/refraction-networking/utls

### Describe the use case of this feature:
some sites may block my request if i'm not visited it by browsers

**Comment by ehsandeep** [comment] 2023-06-17 11:02
Duplicate of https://github.com/projectdiscovery/fastdialer/issues/123

**Closed by ehsandeep** 2023-06-17 11:02 UTC
Labels: Type: Enhancement
